version: "3.1"

services:
  players-db:
    build:
      context: .
      dockerfile: database.txt
    image: players-db:latest
    environment:
      - LANG=en_GB.UTF-8
      - POSTGRES_USER=players
      - POSTGRES_PASSWORD=players
      - POSTGRES_DB=players
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: players-db
    volumes:
      - players-db:/var/lib/postgresql/data/
    networks:
      - net0
    ports:
      - "25432:5432"

  players:
    build:
      context: .
      dockerfile: application.txt
    image: players:latest
    environment:
      - LANG=en_GB.UTF-8
      - SERVER_HOST=0.0.0.0
      - DATABASE_HOST=players-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=players
      - DATABASE_USER=players
      - DATABASE_PASS=players
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: players
    depends_on:
      - players-db
    networks:
      - net0
    ports:
      - "28080:8080"

volumes:
  players-db:

networks:
  net0:

