version: "3.1"

services:
  boards-db:
    build:
      context: .
      dockerfile: database.txt
    image: boards-db:latest
    environment:
      - LANG=en_GB.UTF-8
      - POSTGRES_USER=boards
      - POSTGRES_PASSWORD=boards
      - POSTGRES_DB=boards
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: boards-db
    volumes:
      - boards-db:/var/lib/postgresql/data/
    networks:
      - net0
    ports:
      - "15432:5432"

  boards:
    build:
      context: .
      dockerfile: application.txt
    image: boards:latest
    environment:
      - LANG=en_GB.UTF-8
      - SERVER_HOST=0.0.0.0
      - DATABASE_HOST=boards-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=boards
      - DATABASE_USER=boards
      - DATABASE_PASS=boards
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: boards
    depends_on:
      - boards-db
    networks:
      - net0
    ports:
      - "18080:8080"

volumes:
  boards-db:

networks:
  net0:

