version: "3.1"

services:
  payara-boards-db:
    build:
      context: .
      dockerfile: database.txt
    image: payara-boards-db:latest
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: payara-boards-db
    volumes:
      - payara-boards-db:/var/lib/postgresql/data/
    networks:
      - net0
    environment:
      - LANG=en_GB.UTF-8
      - POSTGRES_USER=payara-boards
      - POSTGRES_PASSWORD=payara-boards
      - POSTGRES_DB=payara-boards
    ports:
      - "15432:5432"

  payara-boards:
    build:
      context: .
      dockerfile: application.txt
    image: payara-boards:latest
    environment:
      - LANG=en_GB.UTF-8
      - DATABASE_HOST=payara-boards-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=payara-boards
      - DATABASE_USERNAME=payara-boards
      - DATABASE_PASSWORD=payara-boards
    restart: always
    deploy:
      restart_policy:
        condition: any
    container_name: payara-boards
    depends_on:
      - payara-boards-db
    networks:
      - net0
    ports:
      - "18080:8080"

volumes:
  payara-boards-db:

networks:
  net0:
